version: '3'
services:
  backend:
    build: .  # Dockerfile からイメージをビルド
    volumes:
      - .:/usr/src/app # ソースコードをボリュームマウント
    working_dir: /usr/src/app/backend # ワークディレクトリを backend に設定
    ports:
      - "8000:8000"  # ポートのマッピングを追加